		SELECT top 1000
			CC.CHSID as MRN ,  /*::KPW_DW::jW changed to use VDW compatible MRN*/
			CAST(ORDER_MED.PAT_ENC_CSN_ID as varchar(18)) AS ENC_ID,
			ORDER_MED.ORDER_MED_ID AS ORDER_ID,  /* required to be unique */
			SUBSTRING(PRESC_ID.PRESC_ID,1,100) as PRESC_ID,
			CAST(ORDER_MED.OLD_ORDER_ID as VARCHAR(18)) AS OLD_ORDER_ID,
			CONVERT(VARCHAR, ORDER_MED.ORDERING_DATE, 110) AS ORDER_DATE ,
			UPPER(SUBSTRING(ZC_DISP_ENC_TYPE.NAME,1,100)) AS ORDER_PLACED_TYPE,
			UPPER(SUBSTRING(ZC_ORDER_CLASS.NAME,1,100)) AS ORDER_CLASS_NAME,
			UPPER(SUBSTRING(ZC_ORDERING_MODE.NAME,1,100)) AS INOUT_FLAG,
			UPPER(SUBSTRING(ZC_ADMIN_ROUTE.NAME,1,100)) AS MED_ROUTE,
			ORDER_MED.MED_PRESC_PROV_ID,
			UPPER(SUBSTRING(ZC_SIMPLE_GENERIC.NAME,1,100)) AS MED_SIMPLE_GEN_NAME,
			CREATRPROV.KP_ORD_CREATR_PROV_ID,
			ORDER_MED.PHARMACY_ID AS KP_PHARMACY_ID,
			ORDER_MED.PANEL_MED_ID AS KP_PANEL_MED_ID,
			ORDER_MED.MEDICATION_ID,
			UPPER(SUBSTRING(ORDER_MED.QUANTITY,1,50)) AS QUANTITY,
			SUBSTRING(ORDER_MED.SIG,1,100) AS SIG,
			UPPER(SUBSTRING(ORDER_MED.REFILLS,1,20)) AS REFILLS,
			ORDER_MED.DISP_AS_WRITTEN_YN,
			CONVERT(VARCHAR, ORDER_MED.START_DATE, 110) AS ORDER_START_DATE,
			CONVERT(VARCHAR, ORDER_MED.END_DATE, 110) AS ORDER_END_DATE,
			DISCONPROV.DISCON_PROV_ID,
			CONVERT(VARCHAR, ORDER_MED.DISCON_TIME, 110) as DISCON_DATE,
			UPPER(SUBSTRING(ZC_RSN_FOR_DISCON.NAME,1,100)) AS DISCON_RSN,
			ORDER_MED.NON_FORMULARY_YN AS KP_NON_FORMULARY_YN,
			UPPER(SUBSTRING(ZC_NONFRM_XCPT_CD.NAME,1,100)) AS KP_NONFRM_XCPT_CD_NAME,
			SUBSTRING(ORDER_MED.MED_COMMENTS,1,250) as KP_MED_COMMENTS
		FROM ORDER_MED
			INNER JOIN IDENTITY_ID ON (ORDER_MED.PAT_ID = IDENTITY_ID.PAT_ID AND IDENTITY_ID.identity_type_id=0) 
      INNER JOIN GHC_Lookup.dbo.CHSID_CONSUMNO CC ON (IDENTITY_ID.IDENTITY_ID=CC.CONSUMNO)   /*::KPW_DW::jW changed to use VDW compatible MRN*/  
      LEFT OUTER JOIN PAT_ENC ON (ORDER_MED.PAT_ENC_CSN_ID = PAT_ENC.PAT_ENC_CSN_ID)
			LEFT OUTER JOIN PRESC_ID ON (ORDER_MED.ORDER_MED_ID = PRESC_ID.ORDER_ID AND PRESC_ID.LINE = 1)
			LEFT OUTER JOIN ZC_ORDERING_MODE ON (ORDER_MED.ORDERING_MODE_C = ZC_ORDERING_MODE.ORDERING_MODE_C)
			LEFT OUTER JOIN ZC_ADMIN_ROUTE ON (ORDER_MED.MED_ROUTE_C = ZC_ADMIN_ROUTE.MED_ROUTE_C)
			LEFT OUTER JOIN ZC_ORDER_CLASS ON (ORDER_MED.ORDER_CLASS_C = ZC_ORDER_CLASS.ORDER_CLASS_C)
			LEFT OUTER JOIN ZC_RSN_FOR_DISCON ON (ORDER_MED.RSN_FOR_DISCON_C = ZC_RSN_FOR_DISCON.RSN_FOR_DISCON_C)
			LEFT OUTER JOIN ZC_DISP_ENC_TYPE ON (PAT_ENC.ENC_TYPE_C = ZC_DISP_ENC_TYPE.DISP_ENC_TYPE_C)
			LEFT OUTER JOIN ZC_NONFRM_XCPT_CD ON (ORDER_MED.NONFRM_XCPT_CD_C = ZC_NONFRM_XCPT_CD.NONFRM_XCPT_CD_C)
			LEFT OUTER JOIN CLARITY_MEDICATION ON (ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID)
			LEFT OUTER JOIN ZC_SIMPLE_GENERIC ON (CLARITY_MEDICATION.SIMPLE_GENERIC_C = ZC_SIMPLE_GENERIC.SIMPLE_GENERIC_C)
			LEFT OUTER JOIN (SELECT PROV_ID AS DISCON_PROV_ID, USER_ID FROM CLARITY_EMP) DISCONPROV ON (ORDER_MED.DISCON_USER_ID=DISCONPROV.[USER_ID])
			LEFT OUTER JOIN (SELECT PROV_ID AS KP_ORD_CREATR_PROV_ID, USER_ID FROM CLARITY_EMP) CREATRPROV ON (ORDER_MED.ORD_CREATR_USER_ID=CREATRPROV.[USER_ID])
		WHERE 
			(ORDER_MED.ORDERING_DATE >= '01-01-2005') and
			(ORDER_MED.IS_PENDING_ORD_YN <> 'Y' OR ORDER_MED.IS_PENDING_ORD_YN IS NULL) AND 
			(ORDER_MED.ORDER_STATUS_C NOT IN (1, 6, 7))